#34 create layout
LexiconGr7-1/gladiator-management-simulator pull request #40
Opened 2022-03-31 07:55 UTC by ipieropan

2022-03-31 10:08 UTC, ipieropan reviewed
Now it's done, next step is the styling. 

`Header` and `Footer` will be called on `Index.js` and `<app />` will be between them, instead of creating a Layout and wrap it.

2022-03-31 11:46 UTC, maqsoodulhasan approved these changes
working

2022-03-31 12:16 UTC, gamo-code requested changes
Refactor and change according to https://github.com/academind/react-complete-guide-code/tree/zz-reactjs-summary/code/19-finished

2022-04-04 07:32 UTC, gamo-code requested changes
Create tests for layout footer header

2022-04-04 07:32 UTC, gamo-code commented on Gladiator.Presentation.Ui/src/Components/Layout/Layout.js
> +      <div>
apply bootstrap container class to div.

2022-04-06 08:16 UTC, gamo-code approved these changes

2022-04-06 10:40 UTC, merged