#46 create gladiator school pages
LexiconGr7-1/gladiator-management-simulator pull request #55
Opened 2022-04-06 11:10 UTC by treox

Creates the following pages and tests:
-SchoolListPage
-SchoolDetailsPage
-SchoolCreatePage
-SchoolEditPage

2022-04-06 11:45 UTC, gamo-code requested changes
Change schoolPages folder name to school (same as for player, naming consistency)

2022-04-06 11:59 UTC, treox reviewed
Fixed: Renamed folder schoolPages to school

2022-04-06 12:07 UTC, gamo-code approved these changes

2022-04-07 08:56 UTC, ipieropan approved these changes

2022-04-07 09:03 UTC, merged